<a href="https://colab.research.google.com/github/Rudra-rudie/RNN-01/blob/main/RNN01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

df.head()

,question,answer
0,What is the capital of France?,Paris
1,What is the capital of Germany?,Berlin
2,Who wrote 'To Kill a Mockingbird'?,Harper-Lee
3,What is the largest planet in our solar system?,Jupiter
4,What is the boiling point of water in Celsius?,100


In [ ]:
#tokenize
def tokenize(text):
  text = text.lower()
  text = text.replace('?', ' ')
  text = text.replace("'", "")
  return text.split()


In [ ]:
tokenize('What is the boiling point of water in Celsius?')

['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius']

In [ ]:

#vocab
vocab = {'<UNK>':0}

In [ ]:
def build_vocab(row):
  print(row['question'],row['answer'])
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])
  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

 # print (tokenized_question, tokenized_answer)

In [ ]:
df.apply(build_vocab, axis=1)

What is the capital of France? Paris
What is the capital of Germany? Berlin
Who wrote 'To Kill a Mockingbird'? Harper-Lee
What is the largest planet in our solar system? Jupiter
What is the boiling point of water in Celsius? 100
Who painted the Mona Lisa? Leonardo-da-Vinci
What is the square root of 64? 8
What is the chemical symbol for gold? Au
Which year did World War II end? 1945
What is the longest river in the world? Nile
What is the capital of Japan? Tokyo
Who developed the theory of relativity? Albert-Einstein
What is the freezing point of water in Fahrenheit? 32
Which planet is known as the Red Planet? Mars
Who is the author of '1984'? George-Orwell
What is the currency of the United Kingdom? Pound
What is the capital of India? Delhi
Who discovered gravity? Newton
How many continents are there on Earth? 7
Which gas do plants use for photosynthesis? CO2
What is the smallest prime number? 2
Who invented the telephone? Alexander-Graham-Bell
What is the capital of Australia? Canber

,0
0,None
1,None
2,None
3,None
4,None
...,...
85,None
86,None
87,None
88,None


In [ ]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'unit

In [ ]:
len(vocab)

324

In [ ]:
#conversion
def text_to_indices(text, vocab):
  indexed_text=[]
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class QADataset(Dataset):
    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab
    def __len__(self):
        return self.df.shape[0]
    def __getitem__(self,index):
        # self.df.iloc[index] # This line was not doing anything, can be removed or implicitly handled by next lines
        numericalized_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
        numericalized_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

        return torch.tensor(numericalized_question), torch.tensor(numericalized_answer)

In [ ]:
dataset = QADataset(df,vocab)

In [ ]:
dataset = QADataset(df,vocab)
dataset[10]

(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [ ]:
dataloader= DataLoader(dataset, batch_size=1, shuffle=True)

In [ ]:
for question, answer in dataloader:
  print(question, answer)

tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[ 10,  29, 130, 131]]) tensor([[

In [ ]:
 import torch.nn as nn

In [ ]:
class SimpleNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64)
    self.fc = nn.Linear(64, vocab_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, question):
    embedded = self.embedding(question)
    output, hidden = self.rnn(embedded)
    output = self.fc(output)
    # The forward pass logic would go here, taking an input 'x'
    return output

In [ ]:
a = x(dataset[0][0].long())

In [ ]:
a = x(dataset[0][0])

In [ ]:
y = nn.RNN(50,64)

In [ ]:
print(f"Shape of 'a' before RNN: {a.shape}")
print(f"Last dimension of 'a' before RNN: {a.size(-1)}")
y(a)

Shape of 'a' before RNN: torch.Size([6, 50])
Last dimension of 'a' before RNN: 50


(tensor([[ 5.5401e-01,  1.9081e-01,  8.5116e-03, -3.5920e-01,  2.4056e-01,
           5.9345e-01, -3.6784e-01, -2.2223e-01, -2.1636e-01,  7.5029e-01,
          -3.1147e-01,  1.2056e-01,  2.5609e-01,  2.5749e-01, -2.5278e-01,
          -1.0423e-01,  8.0931e-01,  2.7781e-01, -7.8059e-01, -8.8724e-02,
          -1.4242e-01,  5.5975e-01,  9.1053e-02, -6.5654e-01,  6.3162e-01,
           7.1690e-01,  4.1784e-01, -7.9628e-02, -7.0323e-01, -3.7468e-01,
           3.0424e-01, -5.7182e-02, -7.5154e-01,  1.3576e-01,  4.4423e-01,
           7.0530e-01,  7.1435e-04,  2.8914e-01,  4.2635e-01,  1.8026e-01,
          -9.5965e-02, -5.1166e-01, -1.7773e-01, -2.4615e-01, -1.9695e-01,
           3.7077e-01,  6.5249e-01,  2.6905e-01, -8.3913e-02,  1.9560e-01,
          -3.2070e-02,  4.2597e-01,  3.4668e-01,  8.6777e-02, -9.1486e-02,
          -4.2942e-02, -8.3585e-01, -5.9397e-01, -6.6350e-01, -2.3961e-01,
          -6.1699e-01,  3.6343e-01,  8.6641e-01, -6.3722e-01],
         [ 1.1916e-01, -5.9076e-01, -

In [ ]:
y(a)

(tensor([[ 5.5401e-01,  1.9081e-01,  8.5116e-03, -3.5920e-01,  2.4056e-01,
           5.9345e-01, -3.6784e-01, -2.2223e-01, -2.1636e-01,  7.5029e-01,
          -3.1147e-01,  1.2056e-01,  2.5609e-01,  2.5749e-01, -2.5278e-01,
          -1.0423e-01,  8.0931e-01,  2.7781e-01, -7.8059e-01, -8.8724e-02,
          -1.4242e-01,  5.5975e-01,  9.1053e-02, -6.5654e-01,  6.3162e-01,
           7.1690e-01,  4.1784e-01, -7.9628e-02, -7.0323e-01, -3.7468e-01,
           3.0424e-01, -5.7182e-02, -7.5154e-01,  1.3576e-01,  4.4423e-01,
           7.0530e-01,  7.1435e-04,  2.8914e-01,  4.2635e-01,  1.8026e-01,
          -9.5965e-02, -5.1166e-01, -1.7773e-01, -2.4615e-01, -1.9695e-01,
           3.7077e-01,  6.5249e-01,  2.6905e-01, -8.3913e-02,  1.9560e-01,
          -3.2070e-02,  4.2597e-01,  3.4668e-01,  8.6777e-02, -9.1486e-02,
          -4.2942e-02, -8.3585e-01, -5.9397e-01, -6.6350e-01, -2.3961e-01,
          -6.1699e-01,  3.6343e-01,  8.6641e-01, -6.3722e-01],
         [ 1.1916e-01, -5.9076e-01, -

In [ ]:
b, h = y(a)

In [ ]:
z = nn.Linear(64,324)

In [ ]:
z(b)

tensor([[ 0.4596, -0.0354, -0.1195,  ...,  0.1003,  0.3644, -0.2674],
        [-0.1100,  0.1216,  0.0841,  ...,  0.2289, -0.0068,  0.1316],
        [ 0.0357,  0.4911, -0.1851,  ...,  0.3293,  0.4753, -0.2160],
        [-0.0027,  0.0824, -0.1033,  ...,  0.1162,  0.0304,  0.0385],
        [ 0.0006,  0.2563,  0.2202,  ...,  0.2112,  0.3352,  0.0442],
        [ 0.2180, -0.1296,  0.1594,  ...,  0.5474, -0.0401,  0.4520]],
       grad_fn=<AddmmBackward0>)

In [ ]:
class SimpleNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64)
    self.fc = nn.Linear(64, vocab_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, question):
    embedded = self.embedding(question)
    output, hidden = self.rnn(embedded)
    output = self.fc(output)
    # The forward pass logic would go here, taking an input 'x'
    return output

In [ ]:
learning_rate = 0.001
epochs = 20

In [ ]:
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim=50, hidden_size=100):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(embedding_dim, hidden_size, batch_first=True) # Changed to LSTM
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x.long())
        out, (h, c) = self.rnn(x) # LSTM returns (output, (h_n, c_n))
        out = self.fc(h.squeeze(0))
        return out

In [ ]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN (50,64, batch_first=True)
z = nn.Linear(64,324)

a = dataset[0][0].unsqueeze(0).long() # Corrected: used .unsqueeze(0) to add batch dimension and .long() for embedding input
print('shape of a:',a.shape)
b = x(a)
print('shape of b:',b.shape)
c, h = y(b)
print('shape of c:',c.shape)
d = z(c.squeeze(0)) # Corrected: typo 'squeze' to 'squeeze' and assignment to method call
print('shape of d:',d.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([6, 324])


In [ ]:
model = SimpleRNN(len(vocab))

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), learning_rate)

In [ ]:
for epoch in range(epochs):
    total_loss = 0

    for question, answer in dataloader:
        optimizer.zero_grad()

        output = model(question)  # model returns (batch_size, 1, vocab_size)
        loss = criterion(output, answer.squeeze(0))  # output is (1, vocab_size), answer.squeeze(0) is (1,)

        loss.backward()

        optimizer.step()

        total_loss = total_loss + loss.item()

    print(f"Epoch: {epoch+1}, Loss: {total_loss/len(dataloader):.4f}")

Epoch: 1, Loss: 5.7816
Epoch: 2, Loss: 5.1173
Epoch: 3, Loss: 4.1469
Epoch: 4, Loss: 3.2231
Epoch: 5, Loss: 2.3470
Epoch: 6, Loss: 1.6110
Epoch: 7, Loss: 1.0288
Epoch: 8, Loss: 0.6724
Epoch: 9, Loss: 0.4449
Epoch: 10, Loss: 0.3156
Epoch: 11, Loss: 0.2315
Epoch: 12, Loss: 0.1748
Epoch: 13, Loss: 0.1380
Epoch: 14, Loss: 0.1129
Epoch: 15, Loss: 0.0935
Epoch: 16, Loss: 0.0795
Epoch: 17, Loss: 0.0681
Epoch: 18, Loss: 0.0591
Epoch: 19, Loss: 0.0520
Epoch: 20, Loss: 0.0460


In [ ]:
def predict(model, question, threshold=0.5):
    numerical_question = text_to_indices(question, vocab)
    question_tensor = torch.tensor(numerical_question).unsqueeze(0)  # fixed variable name
    output = model(question_tensor)  # fixed: was passing 'question' instead of 'question_tensor'

    probabilities = torch.nn.functional.softmax(output, dim=1)
    value, index = torch.max(probabilities, dim=1)
    print(numerical_question)

    if value < threshold:
        print("I don't know")
    else:
        print(list(vocab.keys())[index])

In [ ]:
#Just tessting how accurate the model predicts
predict(model,"what is the largest planet in our solar system?")

[1, 2, 3, 17, 18, 19, 20, 21, 22]
jupiter


In [ ]:
#observation
list(vocab.keys())[7]

'paris'

In [ ]:
from torch.nn.utils.rnn import pad_sequence

# collate function
def collate_fn(batch):
    questions, answers = zip(*batch)
    questions = pad_sequence(questions, batch_first=True, padding_value=0)
    answers = torch.stack(answers)
    return questions, answers

# split dataset
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

# dataloaders with collate_fn
train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_data, batch_size=32, collate_fn=collate_fn)

In [ ]:

from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    questions, answers = zip(*batch)
    questions = pad_sequence(questions, batch_first=True, padding_value=0)
    answers = torch.stack(answers)
    return questions, answers

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_data, batch_size=32, collate_fn=collate_fn)

# verify
print(train_loader.collate_fn)  # should NOT say default_collate

<function collate_fn at 0x7d05810c6f20>


In [ ]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    questions, answers = zip(*batch)
    questions = pad_sequence(questions, batch_first=True, padding_value=0)
    answers = torch.stack(answers)
    return questions, answers

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_data, batch_size=32, collate_fn=collate_fn)

for epoch in range(epochs):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for question, answer in train_loader:
        optimizer.zero_grad()
        output = model(question)
        loss = criterion(output, answer.squeeze(1))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        probabilities = torch.nn.functional.softmax(output, dim=1)
        _, predicted = torch.max(probabilities, dim=1)
        correct += (predicted == answer.squeeze()).sum().item()
        total += answer.size(0)

    train_accuracy = correct / total * 100

    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for question, answer in test_loader:
            output = model(question)
            probabilities = torch.nn.functional.softmax(output, dim=1)
            _, predicted = torch.max(probabilities, dim=1)
            correct += (predicted == answer.squeeze()).sum().item()
            total += answer.size(0)

    test_accuracy = correct / total * 100
    print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(train_loader):.4f} | Train Acc: {train_accuracy:.2f}% | Test Acc: {test_accuracy:.2f}%")

Epoch 1/20 | Loss: 2.0082 | Train Acc: 58.33% | Test Acc: 83.33%
Epoch 2/20 | Loss: 1.2926 | Train Acc: 65.28% | Test Acc: 83.33%
Epoch 3/20 | Loss: 0.9066 | Train Acc: 84.72% | Test Acc: 83.33%
Epoch 4/20 | Loss: 0.7119 | Train Acc: 91.67% | Test Acc: 83.33%
Epoch 5/20 | Loss: 0.5572 | Train Acc: 95.83% | Test Acc: 88.89%
Epoch 6/20 | Loss: 0.5056 | Train Acc: 95.83% | Test Acc: 94.44%
Epoch 7/20 | Loss: 0.4376 | Train Acc: 97.22% | Test Acc: 94.44%
Epoch 8/20 | Loss: 0.3918 | Train Acc: 97.22% | Test Acc: 94.44%
Epoch 9/20 | Loss: 0.2597 | Train Acc: 98.61% | Test Acc: 100.00%
Epoch 10/20 | Loss: 0.2334 | Train Acc: 98.61% | Test Acc: 100.00%
Epoch 11/20 | Loss: 0.2192 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 12/20 | Loss: 0.1722 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 13/20 | Loss: 0.1541 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 14/20 | Loss: 0.1322 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 15/20 | Loss: 0.1128 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 1